drop table if exists member CASCADE;
create table member
(
    id bigint generated by default as identity,
    login_id varchar(20),
    password varchar(20),
    name varchar(20),
    primary key (id)
);

drop table if exists location CASCADE;
create table location
(
    id bigint,
    date_time DATE,
    departure varchar(10),
    destination varchar(20),
    primary key (id,date_time),
    foreign key(id) references member(id)
);